export const restList = [
    {
        id: "1",
        name: "Kushas",
        dbname: "kushas",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8353465, // Hard-coded Latitude
        lng: 78.0217188, // Hard-coded Longitude
        rating: "4.2",
        image: "/2.jpg",
    },
    {
        id: "2",
        name: "KNL",
        dbname: "knl",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8324,
        lng: 78.046824,
        rating: "4.1",
        image: "/2.jpg",
    },
    {
        id: "3",
        name: "Snow Field",
        dbname: "snowfield",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8302831,
        lng: 78.0401789,
        rating: "4.5",
        image: "/2.jpg",
    },
    {
        id: "5",
        name: "mayuri",
        dbname: "mayuri",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8302831,
        lng: 78.0401789,
        rating: "4.5",
        image: "/2.jpg",
    },
    {
        id: "4",
        name: "bros",
        dbname: "bros",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8061586,
        lng: 78.0477663,
        rating: "4.5",
        image: "/2.jpg",
    },
]