export const restList = [
    {
        id: "1",
        name: "Kushas",
        dbname: "kushas",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8353465, // Hard-coded Latitude
        lng: 78.0217188, // Hard-coded Longitude
        rating: "4.2",
        image: "/2.jpg",
    },
    {
        id: "2",
        name: "KNL",
        dbname: "knl",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8324,
        lng: 78.046824,
        rating: "4.1",
        image: "/knl.jpg",
    },
    {
        id: "3",
        name: "Snow Field",
        dbname: "snowfield",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8302831,
        lng: 78.0401789,
        rating: "4.5",
        image: "/snow.jpg",
    },
    {
        id: "4",
        name: "mayuri",
        dbname: "mayuri",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8302831,
        lng: 78.0401789,
        rating: "4.5",
        image: "/mayur.jpg",
    },
    {
        id: "5",
        name: "bros",
        dbname: "bros",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8061586,
        lng: 78.0477663,
        rating: "4.5",
        image: "/burger.jpg",
    },
      {
        id: "6",
        name: "Cake wala",
        dbname: "cake wala",
        type: "veg",
        place: "Venkata Ramana Colony",
        lat: 15.8061586,
        lng: 78.0477663,
        rating: "4.5",
        image: "/sai.jpg",
    },
     {
        id: "7",
        name: "Cream Stone",
        dbname: "cream stone",
        type: "non-veg",
        place: "Venkata Ramana Colony",
        lat: 15.8061586,
        lng: 78.0477663,
        rating: "4.5",
        image: "/pv.jpg",
    },

]