export const Data = [
    { id: 101, name: "ALOO 65", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (101).webp" },
    { id: 102, name: "Gobi Manchurian", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (102).webp" },
    { id: 103, name: "Gobi 65", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (103).webp" },
    { id: 104, name: "Chilli Gobi", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (105).webp" },
    { id: 105, name: "Paneer Butter Masala", price: 220, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (105).webp" },
    { id: 106, name: "Chicken Biryani", price: 250, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (106).webp" },
    { id: 107, name: "Veg Biryani", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (107).webp" },
    { id: 108, name: "Mutton Curry", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (108).webp" },
    { id: 109, name: "Dal Tadka", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (109).webp" },
    { id: 110, name: "Fish Fry", price: 230, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (110).webp" },
    { id: 111, name: "Veg Fried Rice", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (111).webp" },
    { id: 112, name: "Egg Curry", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (112).webp" },
    { id: 113, name: "Masala Dosa", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (113).webp" },
    { id: 114, name: "Chicken 65", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (115).webp" },
    { id: 115, name: "Veg Pulao", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (115).webp" },
    { id: 116, name: "Prawn Curry", price: 260, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (116).webp" },
    { id: 117, name: "Chole Bhature", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (117).webp" },
    { id: 118, name: "Chicken Curry", price: 250, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (118).webp" },
    { id: 119, name: "Rajma Chawal", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (119).webp" },
    { id: 120, name: "Mutton Biryani", price: 300, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (120).webp" },
    { id: 121, name: "Palak Paneer", price: 210, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (121).webp" },
    { id: 122, name: "Tandoori Chicken", price: 270, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (122).webp" },
    { id: 123, name: "Veg Hakka Noodles", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (123).webp" },
    { id: 124, name: "Mutton Rogan Josh", price: 320, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (125).webp" },
    { id: 125, name: "Aloo Paratha", price: 100, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (125).webp" },
    { id: 126, name: "Paneer Tikka", price: 220, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (126).webp" },
    { id: 127, name: "Butter Chicken", price: 270, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (127).webp" },
    { id: 128, name: "Veg Kofta Curry", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (128).webp" },
    { id: 129, name: "Mutton Keema", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (129).webp" },
    { id: 130, name: "Veg Spring Roll", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (130).webp" },
    { id: 131, name: "Chicken Shawarma", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (131).webp" },
    { id: 132, name: "Paneer Bhurji", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (132).webp" },
    { id: 133, name: "Fish Biryani", price: 260, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (133).webp" },
    { id: 134, name: "Veg Kurma", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (135).webp" },
    { id: 135, name: "Egg Fried Rice", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (135).webp" },
    { id: 136, name: "Paneer Pakora", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (136).webp" },
    { id: 137, name: "Chicken Pakora", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (137).webp" },
    { id: 138, name: "Veg Momos", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (138).webp" },
    { id: 139, name: "Chicken Momos", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (139).webp" },
    { id: 140, name: "Paneer Manchurian", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (150).webp" },
    { id: 141, name: "Mutton Korma", price: 290, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (151).webp" },
    { id: 142, name: "Veg Sandwich", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (152).webp" },
    { id: 143, name: "Chicken Sandwich", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (153).webp" },
    { id: 144, name: "Veg Burger", price: 130, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (155).webp" },
    { id: 145, name: "Chicken Burger", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (155).webp" },
    { id: 146, name: "Paneer Pizza", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (156).webp" },
    { id: 147, name: "Chicken Pizza", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (157).webp" },
    { id: 148, name: "Veg Wrap", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (158).webp" },
    { id: 149, name: "Chicken Wrap", price: 170, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (159).webp" },
    { id: 150, name: "Paneer Frankie", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (150).webp" },
    { id: 151, name: "Egg Frankie", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (151).webp" },
    { id: 152, name: "Veg Soup", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (152).webp" },
    { id: 153, name: "Chicken Soup", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (153).webp" },
    { id: 154, name: "Paneer Roll", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (155).webp" },
    { id: 155, name: "Mutton Roll", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (155).webp" },
    { id: 156, name: "Veg Thali", price: 250, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (156).webp" },
    { id: 157, name: "Non-Veg Thali", price: 300, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (157).webp" },
    { id: 158, name: "Paneer Masala Dosa", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (158).webp" },
    { id: 159, name: "Chicken Dosa", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (159).webp" },
    { id: 160, name: "Veg Uttapam", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (160).webp" },
    { id: 161, name: "Egg Uttapam", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (161).webp" },
    { id: 162, name: "Paneer Kulcha", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (162).webp" },
    { id: 163, name: "Keema Kulcha", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (163).webp" },
    { id: 164, name: "Veg Pani Puri", price: 100, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (165).webp" },
    { id: 165, name: "Chicken Pani Puri", price: 130, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (165).webp" },
    { id: 166, name: "Paneer Pulao", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (166).webp" },
    { id: 167, name: "Chicken Pulao", price: 220, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (167).webp" },
    { id: 168, name: "Veg Kebab", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (168).webp" },
    { id: 169, name: "Chicken Kebab", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (169).webp" },
    { id: 170, name: "Paneer Biryani", price: 210, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (170).webp" },
    { id: 171, name: "Mutton Biryani Special", price: 320, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (171).webp" },
    { id: 172, name: "Veg Chowmein", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (172).webp" },
    { id: 173, name: "Chicken Chowmein", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (173).webp" },
    { id: 174, name: "Paneer Cutlet", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (175).webp" },
    { id: 175, name: "Fish Cutlet", price: 180, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (175).webp" },
    { id: 176, name: "Veg Manchow Soup", price: 130, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (176).webp" },
    { id: 177, name: "Chicken Manchow Soup", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (177).webp" },
    { id: 178, name: "Paneer Chilli", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (178).webp" },
    { id: 179, name: "Chicken Chilli", price: 220, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (179).webp" },
    { id: 180, name: "Veg Kurkure Momos", price: 150, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (180).webp" },
    { id: 181, name: "Chicken Kurkure Momos", price: 160, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (181).webp" },
    { id: 182, name: "Paneer Bhatura", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (182).webp" },
    { id: 183, name: "Keema Bhatura", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (183).webp" },
    { id: 184, name: "Veg Idli", price: 120, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (185).webp" },
    { id: 185, name: "Chicken Idli", price: 150, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (185).webp" },
    { id: 186, name: "Paneer Masala", price: 210, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (186).webp" },
    { id: 187, name: "Chicken Masala", price: 250, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (187).webp" },
    { id: 188, name: "Veg Stew", price: 160, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (188).webp" },
    { id: 189, name: "Mutton Stew", price: 280, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (189).webp" },
    { id: 190, name: "Paneer Curry", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (190).webp" },
    { id: 191, name: "Fish Curry Special", price: 260, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (191).webp" },
    { id: 192, name: "Veg Masala Rice", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (192).webp" },
    { id: 193, name: "Egg Masala Rice", price: 190, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (193).webp" },
    { id: 194, name: "Paneer Pulusu", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (195).webp" },
    { id: 195, name: "Chicken Pulusu", price: 220, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (195).webp" },
    { id: 196, name: "Veg Kurma Special", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (196).webp" },
    { id: 197, name: "Mutton Kurma Special", price: 300, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (197).webp" },
    { id: 198, name: "Paneer Bhaji", price: 170, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (198).webp" },
    { id: 199, name: "Chicken Bhaji", price: 200, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (199).webp" },
    { id: 200, name: "Veg Pulav Special", price: 180, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
    { id: 201, name: "Fish Pulav Special", price: 250, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (201).webp" },
    { id: 202, name: "Paneer Masala Fry", price: 200, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (202).webp" },
    { id: 203, name: "Chicken Masala Fry", price: 230, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (203).webp" },
    { id: 204, name: "Veg Special Curry", price: 190, restid: 2, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (205).webp" },
    { id: 205, name: "Mutton Special Curry", price: 310, restid: 2, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (205).webp" }
];