export const Data = [
    { id: 311, name: "Veg Cheese Pizza", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (311).webp" },
    { id: 312, name: "Veg Corn Pizza", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (312).webp" },
    { id: 313, name: "Chicken Burger", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (313).webp" },
    { id: 314, name: "Garlic Bread", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (314).webp" },
    { id: 315, name: "Paneer Butter Masala", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (315).webp" },
    { id: 316, name: "Chicken Biryani", price: 250, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (316).webp" },
    { id: 317, name: "Veg Biryani", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (317).webp" },
    { id: 318, name: "Mutton Curry", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (318).webp" },
    { id: 319, name: "Dal Tadka", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (319).webp" },
    { id: 320, name: "Fish Fry", price: 230, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (320).webp" },
    { id: 321, name: "Veg Fried Rice", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (321).webp" },
    { id: 322, name: "Egg Curry", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (322).webp" },
    { id: 323, name: "Masala Dosa", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (323).webp" },
    { id: 324, name: "Chicken 65", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (324).webp" },
    { id: 325, name: "Veg Pulao", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (325).webp" },
    { id: 326, name: "Prawn Curry", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (326).webp" },
    { id: 327, name: "Chole Bhature", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (327).webp" },
    { id: 328, name: "Chicken Curry", price: 250, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (328).webp" },
    { id: 329, name: "Rajma Chawal", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (329).webp" },
    { id: 330, name: "Mutton Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (330).webp" },
    { id: 331, name: "Palak Paneer", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (331).webp" },
    { id: 332, name: "Tandoori Chicken", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (332).webp" },
    { id: 333, name: "Veg Hakka Noodles", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (333).webp" },
    { id: 334, name: "Mutton Rogan Josh", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (334).webp" },
    { id: 335, name: "Aloo Paratha", price: 100, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (335).webp" },
    { id: 336, name: "Paneer Tikka", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (336).webp" },
    { id: 337, name: "Butter Chicken", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (337).webp" },
    { id: 338, name: "Veg Kofta Curry", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (338).webp" },
    { id: 339, name: "Mutton Keema", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (339).webp" },
    { id: 340, name: "Veg Spring Roll", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (340).webp" },
    { id: 341, name: "Chicken Shawarma", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (341).webp" },
    { id: 342, name: "Paneer Bhurji", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (342).webp" },
    { id: 343, name: "Fish Biryani", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (343).webp" },
    { id: 344, name: "Veg Kurma", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (344).webp" },
    { id: 345, name: "Egg Fried Rice", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (345).webp" },
    { id: 346, name: "Paneer Pakora", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (346).webp" },
    { id: 347, name: "Chicken Pakora", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (347).webp" },
    { id: 348, name: "Veg Momos", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (348).webp" },
    { id: 349, name: "Chicken Momos", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (349).webp" },
    { id: 350, name: "Paneer Manchurian", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (350).webp" },
    { id: 351, name: "Mutton Korma", price: 290, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (351).webp" },
    { id: 352, name: "Veg Sandwich", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (352).webp" },
    { id: 353, name: "Chicken Sandwich", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (353).webp" },
    { id: 354, name: "Paneer Burger", price: 130, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (354).webp" },
    { id: 355, name: "Chicken Burger Deluxe", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (355).webp" },
    { id: 356, name: "Paneer Pizza", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (356).webp" },
    { id: 357, name: "Chicken Pizza", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (357).webp" },
    { id: 358, name: "Veg Wrap", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (358).webp" },
    { id: 359, name: "Chicken Wrap", price: 170, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (359).webp" },
    { id: 360, name: "Paneer Frankie", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (360).webp" },
    { id: 361, name: "Egg Frankie", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (361).webp" },
    { id: 362, name: "Veg Soup", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (362).webp" },
    { id: 363, name: "Chicken Soup", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (363).webp" },
    { id: 364, name: "Paneer Roll", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (364).webp" },
    { id: 365, name: "Mutton Roll", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (365).webp" },
    { id: 366, name: "Veg Thali", price: 250, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (366).webp" },
    { id: 367, name: "Non-Veg Thali", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (367).webp" },
    { id: 368, name: "Paneer Masala Dosa", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (368).webp" },
    { id: 369, name: "Chicken Dosa", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (369).webp" },
    { id: 370, name: "Veg Uttapam", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (370).webp" },
    { id: 371, name: "Egg Uttapam", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (371).webp" },
    { id: 372, name: "Paneer Kulcha", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (372).webp" },
    { id: 373, name: "Keema Kulcha", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (373).webp" },
    { id: 374, name: "Veg Pani Puri", price: 100, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (374).webp" },
    { id: 375, name: "Chicken Pani Puri", price: 130, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (375).webp" },
    { id: 376, name: "Paneer Pulao", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (376).webp" },
    { id: 377, name: "Chicken Pulao", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (377).webp" },
    { id: 378, name: "Veg Kebab", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (378).webp" },
    { id: 379, name: "Chicken Kebab", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (379).webp" },
    { id: 380, name: "Paneer Biryani", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (380).webp" },
    { id: 381, name: "Mutton Biryani Special", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (381).webp" },
    { id: 382, name: "Veg Chowmein", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (382).webp" },
    { id: 383, name: "Chicken Chowmein", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (383).webp" },
    { id: 384, name: "Paneer Cutlet", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (384).webp" },
    { id: 385, name: "Fish Cutlet", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (385).webp" },
    { id: 386, name: "Veg Manchow Soup", price: 130, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (386).webp" },
    { id: 387, name: "Chicken Manchow Soup", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (387).webp" },
    { id: 388, name: "Paneer Chilli", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (388).webp" },
    { id: 389, name: "Chicken Chilli", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (389).webp" },
    { id: 390, name: "Veg Kurkure Momos", price: 150, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (390).webp" },
    { id: 391, name: "Chicken Kurkure Momos", price: 160, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (391).webp" },
    { id: 392, name: "Paneer Bhatura", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (392).webp" },
    { id: 393, name: "Keema Bhatura", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (393).webp" },
    { id: 394, name: "Veg Idli", price: 120, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (394).webp" },
    { id: 395, name: "Egg Idli", price: 150, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (395).webp" },
    { id: 396, name: "Paneer Masala", price: 210, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (396).webp" },
    { id: 397, name: "Chicken Masala", price: 250, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (397).webp" },
    { id: 398, name: "Veg Stew", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (398).webp" },
    { id: 399, name: "Mutton Stew", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (399).webp" },
    { id: 400, name: "Paneer Curry", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (400).webp" },
    { id: 401, name: "Fish Curry Special", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (401).webp" },
    { id: 402, name: "Veg Masala Rice", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (402).webp" },
    { id: 403, name: "Egg Masala Rice", price: 190, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (403).webp" },
    { id: 404, name: "Paneer Pulusu", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (404).webp" },
    { id: 405, name: "Chicken Pulusu", price: 220, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (405).webp" },
    { id: 406, name: "Veg Kurma Special", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (406).webp" },
    { id: 407, name: "Mutton Kurma Special", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (407).webp" },
    { id: 408, name: "Paneer Bhaji", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (408).webp" },
    { id: 409, name: "Chicken Bhaji", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (409).webp" },
    { id: 410, name: "Veg Pulav Special", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (410).webp" },
    { id: 411, name: "Fish Pulav Special", price: 250, restid: 5, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (411).webp" }
];