export const Data = [
 
////hotel taj Darbar
// CHICKEN - Dry
{ id: 1363, name: "Chicken 65", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1364, name: "Chicken Lollipop (3pc)", price: 180, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1365, name: "Chicken Lollipop (6pc)", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1366, name: "Chicken Manchuria", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1367, name: "Chicken Chilli", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1368, name: "Chicken Majestic", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1369, name: "Chicken 555", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1370, name: "Dragon Chicken", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1371, name: "Garlic Chicken", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1372, name: "Chicken shezwan", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1373, name: "Chicken Drumstick", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1374, name: "Honey Chicken", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1375, name: "Peri Peri Chicken", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1376, name: "Ginger Chicken", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1377, name: "Lemon Chicken", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1378, name: "Slice Chicken", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1379, name: "Chicken Gulzar", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1380, name: "Chicken Shangrilla", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1381, name: "Chicken Pataka", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1382, name: "KFC Chicken", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1383, name: "Chicken Apollo", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// VEG ITEMS - Dry
{ id: 1384, name: "Veg Manchuria", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1385, name: "Paneer Manchuria", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1386, name: "Paneer Chilly", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1387, name: "Paneer 65", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1388, name: "Peri Peri Paneer", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1389, name: "Chilly Mushroom", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1390, name: "Mushroom Manchuria", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1391, name: "Mushroom 65", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1392, name: "Chilly Baby Corn", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1393, name: "Baby Corn 65", price: 190, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1394, name: "Gobi Manchuria", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1395, name: "Gobi 65", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1396, name: "Crispy Veg", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1397, name: "Veg Spring Roll", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1398, name: "Veg Lollipop", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1399, name: "Veg Sanghai Roll", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
// MUTTON - Starters
{ id: 1400, name: "Mutton Kheema", price: 320, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1401, name: "Mutton Chilli", price: 360, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1402, name: "Mutton Ghee Roast", price: 370, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// SEA FOOD - Starters
{ id: 1403, name: "Apollo Fish", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1404, name: "Fish 65", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1405, name: "Peri Peri Prawns", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1406, name: "Prawns 65", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// BIRYANI - Chicken
{ id: 1407, name: "Single Piece Biryani", price: 100, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1408, name: "Single Roast Biryani", price: 120, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1409, name: "SPL Chicken Biryani (Mini)", price: 150, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1410, name: "Chicken Biryani (Full)", price: 200, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1411, name: "Chicken Roast Biryani (Full)", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1412, name: "SPL Chicken 65 Biryani (Full)", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1413, name: "Chicken Family Pack (5pc + 2 Egg)", price: 500, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1414, name: "Chicken Jumbo Pack (7pc + 2 Egg + Half 65 + Rumali Roti-2)", price: 900, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// BIRYANI - Mutton
{ id: 1415, name: "Mutton Roast Biryani", price: 300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1416, name: "Mutton Kheema Biryani", price: 300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1417, name: "Mutton Biryani", price: 300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1418, name: "Mutton Family Pack (16pc)", price: 800, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1419, name: "Mutton Jumbo (28pc + Half 65 + Rumali Roti-2)", price: 1300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// Veg Biryani
{ id: 1420, name: "Veg Biryani", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1421, name: "Paneer Biryani", price: 220, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1422, name: "Baby Corn Masala Biryani", price: 220, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1423, name: "Mushroom Biryani", price: 220, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
// Others
{ id: 1424, name: "Biryani Rice", price: 150, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1425, name: "Fish Biryani", price: 320, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1426, name: "Prawns Biryani", price: 320, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1427, name: "TD Special Mix Non Veg Biryani (Chicken 2pc, Mutton 2pc, Fish 4pc, Prawns 4pc)", price: 900, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// ROTI, NAAN
{ id: 1428, name: "Tandoori Roti", price: 30, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1429, name: "Rumali Roti", price: 40, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1430, name: "Butter Naan", price: 50, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1431, name: "Butter Roti", price: 50, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1432, name: "Plain Naan", price: 40, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1433, name: "Garlic Naan", price: 50, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1434, name: "Paratha", price: 30, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1435, name: "Masala Kulcha", price: 50, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
// Gravy - Chicken
{ id: 1436, name: "Chicken Kaju", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1437, name: "Chicken Achari", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1438, name: "Chicken Kadai", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1439, name: "Chicken Hyderabadi", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1440, name: "Chicken Andhra", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1441, name: "Chicken Butter", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1442, name: "Chicken Afghani", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1443, name: "Chicken Tikka Masala", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1444, name: "Chicken Mughlai", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1445, name: "Chicken Kali Mirchi", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1446, name: "Chicken Methi", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1447, name: "Chicken Rayalaseema", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1448, name: "Chicken Payaza", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1449, name: "Chicken TD Special", price: 240, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1450, name: "Chicken Curry", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1451, name: "Chicken Masala", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1452, name: "Chicken Telangana", price: 220, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// Curry - Prawns & Fish
{ id: 1453, name: "Prawns Curry", price: 330, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1454, name: "Prawns Masala", price: 330, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1455, name: "Kadai Prawns", price: 330, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1456, name: "Fish Curry", price: 330, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1457, name: "Fish Masala", price: 330, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// Curry - Mutton
{ id: 1458, name: "Mutton Curry", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1459, name: "Mutton Masala", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1460, name: "Kadai Mutton", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1461, name: "Mutton Rogan Josh", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// Gravy - Veg
{ id: 1462, name: "Shahi Paneer", price: 250, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1463, name: "Palak Paneer Masala", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1464, name: "Paneer Butter Masala", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1465, name: "Paneer Tikka Masala", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1466, name: "Kaju Paneer", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1467, name: "Kadai Paneer", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1468, name: "Mushroom Curry", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1469, name: "Kadai Mushroom", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1470, name: "Veg Curry", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1471, name: "Kadai Veg", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1472, name: "Mix Veg Curry", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1473, name: "Methi Chaman", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1474, name: "Baby Corn Masala", price: 200, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
// KEBAB'S - Chicken
{ id: 1475, name: "TD Special Chicken Kebab", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1476, name: "Tandoori Chicken (Full)", price: 550, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1477, name: "Tandoori Chicken (Half)", price: 350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1478, name: "Tandoori Chicken (Quarter)", price: 200, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1479, name: "Tangadi Kebab", price: 320, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1480, name: "Chicken Tikka", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1481, name: "Reshmi Kebab", price: 300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1482, name: "Malai Tikka", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1483, name: "Hariyali Kebab", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1484, name: "Banjara Kebab", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1485, name: "Arabian Kebab", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1486, name: "Lucknow Kebab", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1487, name: "Chicken Sheek Kebab", price: 280, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
// KEBAB'S - Tandoori Veg
{ id: 1488, name: "Paneer Tikka", price: 220, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1489, name: "Paneer Garlic Tikka", price: 240, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },

{ id: 1490, name: "Mutton Seekh Kebab", price: 400, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// KABSA - Chicken Kabsa
{ id: 1491, name: "Chicken Kabsa 1Pc (Fry)", price: 300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1492, name: "Chicken Kabsa 1Pc (Juicy)", price: 300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1493, name: "Chicken Kabsa 1Pc (Faham)", price: 330, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1494, name: "Chicken Kabsa 2Pc (Fry)", price: 500, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1495, name: "Chicken Kabsa 2Pc (Juicy)", price: 500, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1496, name: "Chicken Kabsa 2Pc (Faham)", price: 550, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1497, name: "Chicken Kabsa 3Pc (Fry)", price: 660, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1498, name: "Chicken Kabsa 3Pc (Juicy)", price: 660, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1499, name: "Chicken Kabsa 3Pc (Faham)", price: 770, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1500, name: "Chicken Kabsa 4Pc (Fry)", price: 850, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1501, name: "Chicken Kabsa 4Pc (Juicy)", price: 850, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1502, name: "Chicken Kabsa 4Pc (Faham)", price: 920, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// KABSA - Mutton Kabsa
{ id: 1503, name: "Mutton Kabsa 1Pc (Juicy)", price: 420, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1504, name: "Mutton Kabsa 1Pc (Special)", price: 450, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1505, name: "Mutton Kabsa 2Pc (Juicy)", price: 700, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1506, name: "Mutton Kabsa 2Pc (Special)", price: 740, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1507, name: "Mutton Kabsa 3Pc (Juicy)", price: 980, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1508, name: "Mutton Kabsa 3Pc (Special)", price: 1000, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1509, name: "Mutton Kabsa 4Pc (Juicy)", price: 1300, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1510, name: "Mutton Kabsa 4Pc (Special)", price: 1350, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// KABSA - Special Kabsa Non Veg
{ id: 1511, name: "Lollipop Kabsa (3pc)", price: 230, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1512, name: "Chicken 65 Kabsa", price: 230, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// KABSA - Special Kabsa Veg
{ id: 1513, name: "Paneer 65 Kabsa", price: 230, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1514, name: "Mix Veg Kabsa (3 Persons) - Paneer 65, Mushroom 65, Baby Corn 65, Gobi 65", price: 450, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },

// KABSA - Fish & Mix Special
{ id: 1515, name: "Fish Kabsa", price: 400, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// KABSA - Mix Special
{ id: 1516, name: "Mix Special Kabsa (2 Mutton Pc, 1 Chicken Pc, 1 Fish Pc, 1 Kamju Pc)", price: 1400, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// KABSA - Extra
{ id: 1517, name: "Kabsa Rice", price: 120, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1518, name: "Kamju Extra Piece", price: 100, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1519, name: "Mutton Extra Piece", price: 250, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1520, name: "Chicken Extra Piece", price: 180, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// Rice Items - Veg
{ id: 1521, name: "Zeera Fried Rice", price: 130, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1522, name: "Veg Fried Rice", price: 150, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1523, name: "shezwan Veg Fried Rice", price: 160, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1524, name: "Mushroom Fried Rice", price: 170, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1525, name: "Paneer Fried Rice", price: 170, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1526, name: "shezwan Paneer Fried Rice", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1527, name: "Baby Corn Fried Rice", price: 170, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1528, name: "Sch Baby Corn Fried Rice", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1529, name: "Curd Rice", price: 100, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },

// Rice Items - Non Veg
{ id: 1530, name: "Egg Fried Rice", price: 180, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1531, name: "Chicken Fried Rice", price: 200, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1532, name: "shezwan Chicken Fried Rice", price: 210, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1533, name: "Mix Fried Rice (Non Veg)", price: 250, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },

// Noodles - Veg
{ id: 1534, name: "Veg Noodles", price: 150, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1535, name: "Veg shezwan Noodles", price: 160, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1536, name: "Paneer Noodles", price: 170, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1537, name: "shezwan Paneer Noodles", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1538, name: "Baby Corn Noodles", price: 170, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 1539, name: "Sch Baby Corn Noodles", price: 180, restid: 11, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },

// Noodles - Non Veg
{ id: 1540, name: "Egg Noodles", price: 160, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1541, name: "Chicken Noodles", price: 190, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1542, name: "Chicken shezwan Noodles", price: 200, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 1543, name: "Mix Noodles (Non Veg)", price: 250, restid: 11, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
]