export const Data = [
    { id: 206, name: "Veg Cheese Pizza", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (206).webp" },
    { id: 207, name: "Veg Corn Pizza", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (207).webp" },
    { id: 208, name: "Veg Burger", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (208).webp" },
    { id: 209, name: "Garlic Bread", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (209).webp" },
    { id: 210, name: "Paneer Butter Masala", price: 220, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (210).webp" },
    { id: 211, name: "Chicken Biryani", price: 250, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (211).webp" },
    { id: 212, name: "Veg Biryani", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (212).webp" },
    { id: 213, name: "Mutton Curry", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (213).webp" },
    { id: 214, name: "Dal Tadka", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (215).webp" },
    { id: 215, name: "Fish Fry", price: 230, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (215).webp" },
    { id: 216, name: "Veg Fried Rice", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (216).webp" },
    { id: 217, name: "Egg Curry", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (217).webp" },
    { id: 218, name: "Masala Dosa", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (218).webp" },
    { id: 219, name: "Chicken 65", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (219).webp" },
    { id: 220, name: "Veg Pulao", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (220).webp" },
    { id: 221, name: "Prawn Curry", price: 260, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (221).webp" },
    { id: 222, name: "Chole Bhature", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (222).webp" },
    { id: 223, name: "Chicken Curry", price: 250, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (223).webp" },
    { id: 224, name: "Rajma Chawal", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (225).webp" },
    { id: 225, name: "Mutton Biryani", price: 300, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (225).webp" },
    { id: 226, name: "Palak Paneer", price: 210, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (226).webp" },
    { id: 227, name: "Tandoori Chicken", price: 270, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (227).webp" },
    { id: 228, name: "Veg Hakka Noodles", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (228).webp" },
    { id: 229, name: "Mutton Rogan Josh", price: 320, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (229).webp" },
    { id: 230, name: "Aloo Paratha", price: 100, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (230).webp" },
    { id: 231, name: "Paneer Tikka", price: 220, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (231).webp" },
    { id: 232, name: "Butter Chicken", price: 270, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (232).webp" },
    { id: 233, name: "Veg Kofta Curry", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (233).webp" },
    { id: 234, name: "Mutton Keema", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (235).webp" },
    { id: 235, name: "Veg Spring Roll", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (235).webp" },
    { id: 236, name: "Chicken Shawarma", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (236).webp" },
    { id: 237, name: "Paneer Bhurji", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (237).webp" },
    { id: 238, name: "Fish Biryani", price: 260, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (238).webp" },
    { id: 239, name: "Veg Kurma", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (239).webp" },
    { id: 240, name: "Egg Fried Rice", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (250).webp" },
    { id: 241, name: "Paneer Pakora", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (251).webp" },
    { id: 242, name: "Chicken Pakora", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (252).webp" },
    { id: 243, name: "Veg Momos", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (253).webp" },
    { id: 244, name: "Chicken Momos", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (255).webp" },
    { id: 245, name: "Paneer Manchurian", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (255).webp" },
    { id: 246, name: "Mutton Korma", price: 290, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (256).webp" },
    { id: 247, name: "Veg Sandwich", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (257).webp" },
    { id: 248, name: "Chicken Sandwich", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (258).webp" },
    { id: 249, name: "Veg Burger", price: 130, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (259).webp" },
    { id: 250, name: "Chicken Burger", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (250).webp" },
    { id: 251, name: "Paneer Pizza", price: 250, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (251).webp" },
    { id: 252, name: "Chicken Pizza", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (252).webp" },
    { id: 253, name: "Veg Wrap", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (253).webp" },
    { id: 254, name: "Chicken Wrap", price: 170, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (255).webp" },
    { id: 255, name: "Paneer Frankie", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (255).webp" },
    { id: 256, name: "Egg Frankie", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (256).webp" },
    { id: 257, name: "Veg Soup", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (257).webp" },
    { id: 258, name: "Chicken Soup", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (258).webp" },
    { id: 259, name: "Paneer Roll", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (259).webp" },
    { id: 260, name: "Mutton Roll", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (260).webp" },
    { id: 261, name: "Veg Thali", price: 250, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (261).webp" },
    { id: 262, name: "Non-Veg Thali", price: 300, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (262).webp" },
    { id: 263, name: "Paneer Masala Dosa", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (263).webp" },
    { id: 264, name: "Chicken Dosa", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (265).webp" },
    { id: 265, name: "Veg Uttapam", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (265).webp" },
    { id: 266, name: "Egg Uttapam", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (266).webp" },
    { id: 267, name: "Paneer Kulcha", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (267).webp" },
    { id: 268, name: "Keema Kulcha", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (268).webp" },
    { id: 269, name: "Veg Pani Puri", price: 100, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (269).webp" },
    { id: 270, name: "Chicken Pani Puri", price: 130, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (270).webp" },
    { id: 271, name: "Paneer Pulao", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (271).webp" },
    { id: 272, name: "Chicken Pulao", price: 220, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (272).webp" },
    { id: 273, name: "Veg Kebab", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (273).webp" },
    { id: 274, name: "Chicken Kebab", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (275).webp" },
    { id: 275, name: "Paneer Biryani", price: 210, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (275).webp" },
    { id: 276, name: "Mutton Biryani Special", price: 320, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (276).webp" },
    { id: 277, name: "Veg Chowmein", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (277).webp" },
    { id: 278, name: "Chicken Chowmein", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (278).webp" },
    { id: 279, name: "Paneer Cutlet", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (279).webp" },
    { id: 280, name: "Fish Cutlet", price: 180, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (280).webp" },
    { id: 281, name: "Veg Manchow Soup", price: 130, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (281).webp" },
    { id: 282, name: "Chicken Manchow Soup", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (282).webp" },
    { id: 283, name: "Paneer Chilli", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (283).webp" },
    { id: 284, name: "Chicken Chilli", price: 220, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (285).webp" },
    { id: 285, name: "Veg Kurkure Momos", price: 150, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (285).webp" },
    { id: 286, name: "Chicken Kurkure Momos", price: 160, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (286).webp" },
    { id: 287, name: "Paneer Bhatura", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (287).webp" },
    { id: 288, name: "Keema Bhatura", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (288).webp" },
    { id: 289, name: "Veg Idli", price: 120, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (289).webp" },
    { id: 290, name: "Chicken Idli", price: 150, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (290).webp" },
    { id: 291, name: "Paneer Masala", price: 210, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (291).webp" },
    { id: 292, name: "Chicken Masala", price: 250, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (292).webp" },
    { id: 293, name: "Veg Stew", price: 160, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (293).webp" },
    { id: 294, name: "Mutton Stew", price: 280, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (295).webp" },
    { id: 295, name: "Paneer Curry", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (295).webp" },
    { id: 296, name: "Fish Curry Special", price: 260, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (296).webp" },
    { id: 297, name: "Veg Masala Rice", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (297).webp" },
    { id: 298, name: "Egg Masala Rice", price: 190, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (298).webp" },
    { id: 299, name: "Paneer Pulusu", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (299).webp" },
    { id: 300, name: "Chicken Pulusu", price: 220, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (300).webp" },
    { id: 301, name: "Veg Kurma Special", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (301).webp" },
    { id: 302, name: "Mutton Kurma Special", price: 300, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (302).webp" },
    { id: 303, name: "Paneer Bhaji", price: 170, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (303).webp" },
    { id: 304, name: "Chicken Bhaji", price: 200, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (304).webp" },
    { id: 305, name: "Veg Pulav Special", price: 180, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (305).webp" },
    { id: 306, name: "Fish Pulav Special", price: 250, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (306).webp" },
    { id: 307, name: "Paneer Masala Fry", price: 200, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (307).webp" },
    { id: 308, name: "Chicken Masala Fry", price: 230, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (308).webp" },
    { id: 309, name: "Veg Special Curry", price: 190, restid: 3, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (309).webp" },
    { id: 310, name: "Mutton Special Curry", price: 310, restid: 3, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (310).webp" }
];