export const Data = [
    { id: 513, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (13).webp" },
    { id: 514, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (15).webp" },
    { id: 515, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (15).webp" },
    { id: 516, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (16).webp" },
    { id: 517, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (17).webp" },
    { id: 518, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (18).webp" },
    { id: 519, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (19).webp" },
    { id: 520, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (20).webp" },
    { id: 521, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (21).webp" },
    { id: 522, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (22).webp" },
    { id: 523, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (23).webp" },
    { id: 524, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (25).webp" },
    { id: 525, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (25).webp" },
    { id: 526, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (26).webp" },
    { id: 527, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (27).webp" },
    { id: 528, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (28).webp" },
    { id: 529, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (29).webp" },
    { id: 530, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (30).webp" },
    { id: 531, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (31).webp" },
    { id: 532, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (32).webp" },
    { id: 533, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (33).webp" },
    { id: 534, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (35).webp" },
    { id: 535, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (35).webp" },
    { id: 536, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (36).webp" },
    { id: 537, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (37).webp" },
    { id: 538, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (38).webp" },
    { id: 539, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (39).webp" },
    { id: 540, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (50).webp" },
    { id: 541, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (51).webp" },
    { id: 542, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (52).webp" },
    { id: 543, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (53).webp" },
    { id: 545, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (55).webp" },
    { id: 546, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (55).webp" },
    { id: 547, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (56).webp" },
    { id: 548, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (57).webp" },
    { id: 549, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (58).webp" },
    { id: 550, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (59).webp" },
    { id: 551, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (50).webp" },
    { id: 552, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (51).webp" },
    { id: 553, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (52).webp" },
    { id: 554, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (53).webp" },
    { id: 555, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (55).webp" },
    { id: 556, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (55).webp" },
    { id: 557, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (56).webp" },
    { id: 558, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (57).webp" },
    { id: 559, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (58).webp" },
    { id: 560, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (59).webp" },
    { id: 561, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (60).webp" },
    { id: 562, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (61).webp" },
    { id: 563, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (62).webp" },
    { id: 564, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (63).webp" },
    { id: 565, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (65).webp" },
    { id: 566, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (65).webp" },
    { id: 567, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (66).webp" },
    { id: 568, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (67).webp" },
    { id: 569, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (68).webp" },
    { id: 570, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (69).webp" },
    { id: 571, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (71).webp" },
    { id: 572, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (72).webp" },
    { id: 573, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (73).webp" },
    { id: 574, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (75).webp" },
    { id: 575, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (75).webp" },
    { id: 576, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (76).webp" },
    { id: 577, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (77).webp" },
    { id: 578, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (78).webp" },
    { id: 579, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (79).webp" },
    { id: 580, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (80).webp" },
    { id: 581, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (81).webp" },
    { id: 582, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (82).webp" },
    { id: 583, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (83).webp" },
    { id: 584, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (85).webp" },
    { id: 585, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (85).webp" },
    { id: 586, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (86).webp" },
    { id: 587, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (87).webp" },
    { id: 588, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (88).webp" },
    { id: 589, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (89).webp" },
    { id: 590, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (90).webp" },
    { id: 591, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (91).webp" },
    { id: 592, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (92).webp" },
    { id: 593, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (93).webp" },
    { id: 594, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (95).webp" },
    { id: 595, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (95).webp" },
    { id: 596, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (96).webp" },
    { id: 597, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (97).webp" },
    { id: 598, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (98).webp" },
    { id: 599, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (99).webp" },
    { id: 600, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (100).webp" },
    { id: 601, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (101).webp" },
    { id: 602, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (102).webp" },
    { id: 603, name: "Veg Stew", price: 160, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (103).webp" },
    { id: 604, name: "Mutton Stew", price: 280, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (105).webp" },
    { id: 605, name: "Paneer Curry", price: 200, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (105).webp" },
    { id: 606, name: "Fish Curry Special", price: 260, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (106).webp" },
    { id: 607, name: "Veg Masala Rice", price: 170, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (107).webp" },
    { id: 608, name: "Egg Masala Rice", price: 190, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (108).webp" },
    { id: 609, name: "Paneer Pulusu", price: 180, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (109).webp" },
    { id: 610, name: "Chicken Pulusu", price: 220, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (110).webp" },
    { id: 611, name: "Paneer Masala", price: 210, restid: 6, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (111).webp" },
    { id: 612, name: "Chicken Masala", price: 250, restid: 6, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (112).webp" }
];