export const Data = [
    { id: 412, name: "Veg Biryani", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (412).webp" },
    { id: 413, name: "Non-Veg Biryani", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (413).webp" },
    { id: 414, name: "Veg Fried Rice", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (414).webp" },
    { id: 415, name: "Non-Veg Fried Rice", price: 190, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (415).webp" },
    { id: 416, name: "Paneer Butter Masala", price: 220, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (416).webp" },
    { id: 417, name: "Chicken Curry", price: 250, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (417).webp" },
    { id: 418, name: "Veg Pulao", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (418).webp" },
    { id: 419, name: "Mutton Biryani", price: 300, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (419).webp" },
    { id: 420, name: "Dal Tadka", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (420).webp" },
    { id: 421, name: "Fish Fry", price: 230, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (421).webp" },
    { id: 422, name: "Chole Bhature", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (422).webp" },
    { id: 423, name: "Egg Curry", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (423).webp" },
    { id: 424, name: "Rajma Chawal", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (424).webp" },
    { id: 425, name: "Prawn Curry", price: 260, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (425).webp" },
    { id: 426, name: "Palak Paneer", price: 210, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (426).webp" },
    { id: 427, name: "Tandoori Chicken", price: 270, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (427).webp" },
    { id: 428, name: "Veg Hakka Noodles", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (428).webp" },
    { id: 429, name: "Mutton Rogan Josh", price: 320, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (429).webp" },
    { id: 430, name: "Aloo Paratha", price: 100, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (430).webp" },
    { id: 431, name: "Paneer Tikka", price: 220, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (431).webp" },
    { id: 432, name: "Butter Chicken", price: 270, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (432).webp" },
    { id: 433, name: "Veg Kofta Curry", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (433).webp" },
    { id: 434, name: "Mutton Keema", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (434).webp" },
    { id: 435, name: "Veg Spring Roll", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (435).webp" },
    { id: 436, name: "Chicken Shawarma", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (436).webp" },
    { id: 437, name: "Paneer Bhurji", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (437).webp" },
    { id: 438, name: "Fish Biryani", price: 260, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (438).webp" },
    { id: 439, name: "Veg Kurma", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (439).webp" },
    { id: 440, name: "Egg Fried Rice", price: 170, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (440).webp" },
    { id: 441, name: "Paneer Pakora", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (441).webp" },
    { id: 442, name: "Chicken Pakora", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (442).webp" },
    { id: 443, name: "Veg Momos", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (443).webp" },
    { id: 444, name: "Chicken Momos", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (444).webp" },
    { id: 445, name: "Paneer Manchurian", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (445).webp" },
    { id: 446, name: "Mutton Korma", price: 290, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (446).webp" },
    { id: 447, name: "Veg Sandwich", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (447).webp" },
    { id: 448, name: "Chicken Sandwich", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (448).webp" },
    { id: 449, name: "Veg Burger", price: 130, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (449).webp" },
    { id: 450, name: "Chicken Burger", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (450).webp" },
    { id: 451, name: "Paneer Pizza", price: 250, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (451).webp" },
    { id: 452, name: "Chicken Pizza", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (452).webp" },
    { id: 453, name: "Veg Wrap", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (453).webp" },
    { id: 454, name: "Chicken Wrap", price: 170, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (454).webp" },
    { id: 455, name: "Paneer Frankie", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (455).webp" },
    { id: 456, name: "Egg Frankie", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (456).webp" },
    { id: 457, name: "Veg Soup", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (457).webp" },
    { id: 458, name: "Chicken Soup", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (458).webp" },
    { id: 459, name: "Paneer Roll", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (459).webp" },
    { id: 460, name: "Mutton Roll", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (460).webp" },
    { id: 461, name: "Veg Thali", price: 250, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (461).webp" },
    { id: 462, name: "Non-Veg Thali", price: 300, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (462).webp" },
    { id: 463, name: "Paneer Masala Dosa", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (463).webp" },
    { id: 464, name: "Chicken Dosa", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (464).webp" },
    { id: 465, name: "Veg Uttapam", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (465).webp" },
    { id: 466, name: "Egg Uttapam", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (466).webp" },
    { id: 467, name: "Paneer Kulcha", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (467).webp" },
    { id: 468, name: "Keema Kulcha", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (468).webp" },
    { id: 469, name: "Veg Pani Puri", price: 100, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (469).webp" },
    { id: 470, name: "Chicken Pani Puri", price: 130, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (470).webp" },
    { id: 471, name: "Paneer Pulao", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (471).webp" },
    { id: 472, name: "Chicken Pulao", price: 220, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (472).webp" },
    { id: 473, name: "Veg Kebab", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (473).webp" },
    { id: 474, name: "Chicken Kebab", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (474).webp" },
    { id: 475, name: "Paneer Biryani", price: 210, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (475).webp" },
    { id: 476, name: "Mutton Biryani Special", price: 320, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (476).webp" },
    { id: 477, name: "Veg Chowmein", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (477).webp" },
    { id: 478, name: "Chicken Chowmein", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (478).webp" },
    { id: 479, name: "Paneer Cutlet", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (479).webp" },
    { id: 480, name: "Fish Cutlet", price: 180, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (480).webp" },
    { id: 481, name: "Veg Manchow Soup", price: 130, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (481).webp" },
    { id: 482, name: "Chicken Manchow Soup", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (482).webp" },
    { id: 483, name: "Paneer Chilli", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (483).webp" },
    { id: 484, name: "Chicken Chilli", price: 220, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (484).webp" },
    { id: 485, name: "Veg Kurkure Momos", price: 150, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (485).webp" },
    { id: 486, name: "Chicken Kurkure Momos", price: 160, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (486).webp" },
    { id: 487, name: "Paneer Bhatura", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (487).webp" },
    { id: 488, name: "Keema Bhatura", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (488).webp" },
    { id: 489, name: "Veg Idli", price: 120, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (489).webp" },
    { id: 490, name: "Egg Idli", price: 150, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (490).webp" },
    { id: 491, name: "Paneer Masala", price: 210, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (491).webp" },
    { id: 492, name: "Chicken Masala", price: 250, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (492).webp" },
    { id: 493, name: "Veg Stew", price: 160, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (493).webp" },
    { id: 494, name: "Mutton Stew", price: 280, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (494).webp" },
    { id: 495, name: "Paneer Curry", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (495).webp" },
    { id: 496, name: "Fish Curry Special", price: 260, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (496).webp" },
    { id: 497, name: "Veg Masala Rice", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (497).webp" },
    { id: 498, name: "Egg Masala Rice", price: 190, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (498).webp" },
    { id: 499, name: "Paneer Pulusu", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (499).webp" },
    { id: 500, name: "Chicken Pulusu", price: 220, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (500).webp" },
    { id: 501, name: "Veg Kurma Special", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (196).webp" },
    { id: 502, name: "Mutton Kurma Special", price: 300, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (197).webp" },
    { id: 503, name: "Paneer Bhaji", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (198).webp" },
    { id: 504, name: "Chicken Bhaji", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (199).webp" },
    { id: 505, name: "Veg Pulav Special", price: 180, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
    { id: 506, name: "Fish Pulav Special", price: 250, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (201).webp" },
    { id: 507, name: "Paneer Masala Fry", price: 200, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (202).webp" },
    { id: 508, name: "Chicken Masala Fry", price: 230, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (203).webp" },
    { id: 509, name: "Veg Special Curry", price: 190, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (309).webp" },
    { id: 510, name: "Mutton Special Curry", price: 310, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (310).webp" },
    { id: 511, name: "Cheese Corn Pizza", price: 170, restid: 4, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (207).webp" },
    { id: 512, name: "Chicken Tikka Pizza", price: 200, restid: 4, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (157).webp" }
];