export const Data = [
    { id: 613, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (113).webp" },
    { id: 614, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (115).webp" },
    { id: 615, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (115).webp" },
    { id: 616, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (116).webp" },
    { id: 617, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (117).webp" },
    { id: 618, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (118).webp" },
    { id: 619, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (119).webp" },
    { id: 620, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (120).webp" },
    { id: 621, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (121).webp" },
    { id: 622, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (122).webp" },
    { id: 623, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (123).webp" },
    { id: 624, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (125).webp" },
    { id: 625, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (125).webp" },
    { id: 626, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (126).webp" },
    { id: 627, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (127).webp" },
    { id: 628, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (128).webp" },
    { id: 629, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (129).webp" },
    { id: 630, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (130).webp" },
    { id: 631, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (131).webp" },
    { id: 632, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (132).webp" },
    { id: 633, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (133).webp" },
    { id: 634, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (135).webp" },
    { id: 635, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (135).webp" },
    { id: 636, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (136).webp" },
    { id: 637, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (137).webp" },
    { id: 638, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (138).webp" },
    { id: 639, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (139).webp" },
    { id: 640, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (150).webp" },
    { id: 641, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (151).webp" },
    { id: 642, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (152).webp" },
    { id: 643, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (153).webp" },
    { id: 644, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (155).webp" },
    { id: 645, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (155).webp" },
    { id: 646, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (156).webp" },
    { id: 647, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (157).webp" },
    { id: 648, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (158).webp" },
    { id: 649, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (159).webp" },
    { id: 650, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (150).webp" },
    { id: 651, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (151).webp" },
    { id: 652, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (152).webp" },
    { id: 653, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (153).webp" },
    { id: 654, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (155).webp" },
    { id: 655, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (155).webp" },
    { id: 656, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (156).webp" },
    { id: 657, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (157).webp" },
    { id: 658, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (158).webp" },
    { id: 659, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (159).webp" },
    { id: 660, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (160).webp" },
    { id: 661, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (161).webp" },
    { id: 662, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (162).webp" },
    { id: 663, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (163).webp" },
    { id: 664, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (165).webp" },
    { id: 665, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (165).webp" },
    { id: 666, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (166).webp" },
    { id: 667, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (167).webp" },
    { id: 668, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (168).webp" },
    { id: 669, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (169).webp" },
    { id: 670, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (170).webp" },
    { id: 671, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (171).webp" },
    { id: 672, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (172).webp" },
    { id: 673, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (173).webp" },
    { id: 674, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (175).webp" },
    { id: 675, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (175).webp" },
    { id: 676, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (176).webp" },
    { id: 677, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (177).webp" },
    { id: 678, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (178).webp" },
    { id: 679, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (179).webp" },
    { id: 680, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (180).webp" },
    { id: 681, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (181).webp" },
    { id: 682, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (182).webp" },
    { id: 683, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (183).webp" },
    { id: 684, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (185).webp" },
    { id: 685, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (185).webp" },
    { id: 686, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (186).webp" },
    { id: 687, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (187).webp" },
    { id: 688, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (188).webp" },
    { id: 689, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (189).webp" },
    { id: 690, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (190).webp" },
    { id: 691, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (191).webp" },
    { id: 692, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (192).webp" },
    { id: 693, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (193).webp" },
    { id: 694, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (195).webp" },
    { id: 695, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (195).webp" },
    { id: 696, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (196).webp" },
    { id: 697, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (197).webp" },
    { id: 698, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (198).webp" },
    { id: 699, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (199).webp" },
    { id: 700, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
    { id: 701, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (201).webp" },
    { id: 702, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (202).webp" },
    { id: 703, name: "Veg Stew", price: 160, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (203).webp" },
    { id: 704, name: "Mutton Stew", price: 280, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (205).webp" },
    { id: 705, name: "Paneer Curry", price: 200, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (205).webp" },
    { id: 706, name: "Fish Curry Special", price: 260, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (206).webp" },
    { id: 707, name: "Veg Masala Rice", price: 170, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (207).webp" },
    { id: 708, name: "Egg Masala Rice", price: 190, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (208).webp" },
    { id: 709, name: "Paneer Pulusu", price: 180, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (209).webp" },
    { id: 710, name: "Chicken Pulusu", price: 220, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (210).webp" },
    { id: 711, name: "Paneer Masala", price: 210, restid: 7, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (211).webp" },
    { id: 712, name: "Chicken Masala", price: 250, restid: 7, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (212).webp" }
];