import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css';
import Navbar from '@/navigation/page';
import StoreProvider from '../../lib/StoreProvider';
import AuthInitializer from '../../lib/AuthInitializer';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: '/manifest.json'
};

import GlobalServiceCheck from './components/GlobalServiceCheck';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthInitializer />
          <GlobalServiceCheck />
          {children}
          <Navbar />
        </StoreProvider>
      </body>
    </html>
  );
}


