export const Data = [
    { id: 1, name: "ALOO 65 hjsbfgjhbshjbghsrf refhjbgibresg ", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (1).webp" },
    { id: 2, name: "Gobi Manchurian", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (2).webp" },
    { id: 3, name: "Gobi 65", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (3).webp" },
    { id: 4, name: "Chilli Gobi", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (5).webp" },
    { id: 5, name: "Paneer Butter Masala", price: 220, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (5).webp" },
    { id: 6, name: "Chicken Biryani", price: 250, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (6).webp" },
    { id: 7, name: "Veg Biryani", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (7).webp" },
    { id: 8, name: "Mutton Curry", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (8).webp" },
    { id: 9, name: "Dal Tadka", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (9).webp" },
    { id: 10, name: "Fish Fry", price: 230, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (10).webp" },
    { id: 11, name: "Veg Fried Rice", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (11).webp" },
    { id: 12, name: "Egg Curry", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (12).webp" },
    { id: 13, name: "Masala Dosa", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (13).webp" },
    { id: 14, name: "Chicken 65", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (15).webp" },
    { id: 15, name: "Veg Pulao", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (15).webp" },
    { id: 16, name: "Prawn Curry", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (16).webp" },
    { id: 17, name: "Chole Bhature", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (17).webp" },
    { id: 18, name: "Chicken Curry", price: 250, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (18).webp" },
    { id: 19, name: "Rajma Chawal", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (19).webp" },
    { id: 20, name: "Mutton Biryani", price: 300, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (20).webp" },
    { id: 21, name: "Palak Paneer", price: 210, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (21).webp" },
    { id: 22, name: "Tandoori Chicken", price: 270, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (22).webp" },
    { id: 23, name: "Veg Hakka Noodles", price: 180, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (23).webp" },
    { id: 24, name: "Mutton Rogan Josh", price: 320, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (25).webp" },
    { id: 25, name: "Aloo Paratha", price: 100, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (25).webp" },
    { id: 26, name: "Fish Curry", price: 250, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (26).webp" },
    { id: 27, name: "Veg Cutlet", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (27).webp" },
    { id: 28, name: "Egg Biryani", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (28).webp" },
    { id: 29, name: "Bhindi Masala", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (29).webp" },
    { id: 30, name: "Chicken Tikka Masala", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (30).webp" },
    { id: 31, name: "Paneer Tikka", price: 220, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (31).webp" },
    { id: 32, name: "Butter Chicken", price: 270, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (32).webp" },
    { id: 33, name: "Veg Kofta Curry", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (33).webp" },
    { id: 34, name: "Mutton Keema", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (35).webp" },
    { id: 35, name: "Veg Spring Roll", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (35).webp" },
    { id: 36, name: "Chicken Shawarma", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (36).webp" },
    { id: 37, name: "Paneer Bhurji", price: 190, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (37).webp" },
    { id: 38, name: "Fish Biryani", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (38).webp" },
    { id: 39, name: "Veg Kurma", price: 180, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (39).webp" },
    { id: 40, name: "Egg Fried Rice", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (50).webp" },
    { id: 41, name: "Paneer Pakora", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (51).webp" },
    { id: 42, name: "Chicken Pakora", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (52).webp" },
    { id: 43, name: "Veg Momos", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (53).webp" },
    { id: 44, name: "Chicken Momos", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (55).webp" },
    { id: 45, name: "Paneer Manchurian", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (55).webp" },
    { id: 46, name: "Mutton Korma", price: 290, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (56).webp" },
    { id: 47, name: "Veg Sandwich", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (57).webp" },
    { id: 48, name: "Chicken Sandwich", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (58).webp" },
    { id: 49, name: "Veg Burger", price: 130, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (59).webp" },
    { id: 50, name: "Chicken Burger", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (50).webp" },
    { id: 51, name: "Paneer Pizza", price: 250, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (51).webp" },
    { id: 52, name: "Chicken Pizza", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (52).webp" },
    { id: 53, name: "Veg Wrap", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (53).webp" },
    { id: 54, name: "Chicken Wrap", price: 170, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (55).webp" },
    { id: 55, name: "Paneer Frankie", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (55).webp" },
    { id: 56, name: "Egg Frankie", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (56).webp" },
    { id: 57, name: "Veg Soup", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (57).webp" },
    { id: 58, name: "Chicken Soup", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (58).webp" },
    { id: 59, name: "Paneer Roll", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (59).webp" },
    { id: 60, name: "Mutton Roll", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (60).webp" },
    { id: 61, name: "Veg Thali", price: 250, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (61).webp" },
    { id: 62, name: "Non-Veg Thali", price: 300, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (62).webp" },
    { id: 63, name: "Paneer Masala Dosa", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (63).webp" },
    { id: 64, name: "Chicken Dosa", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (65).webp" },
    { id: 65, name: "Veg Uttapam", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (65).webp" },
    { id: 66, name: "Egg Uttapam", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (66).webp" },
    { id: 67, name: "Paneer Kulcha", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (67).webp" },
    { id: 68, name: "Keema Kulcha", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (68).webp" },
    { id: 69, name: "Veg Pani Puri", price: 100, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (69).webp" },
    { id: 70, name: "Chicken Pani Puri", price: 130, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (70).webp" },
    { id: 71, name: "Paneer Pulao", price: 190, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (71).webp" },
    { id: 72, name: "Chicken Pulao", price: 220, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (72).webp" },
    { id: 73, name: "Veg Kebab", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (73).webp" },
    { id: 74, name: "Chicken Kebab", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (75).webp" },
    { id: 75, name: "Paneer Biryani", price: 210, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (75).webp" },
    { id: 76, name: "Mutton Biryani Special", price: 320, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (76).webp" },
    { id: 77, name: "Veg Chowmein", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (77).webp" },
    { id: 78, name: "Chicken Chowmein", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (78).webp" },
    { id: 79, name: "Paneer Cutlet", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (79).webp" },
    { id: 80, name: "Fish Cutlet", price: 180, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (80).webp" },
    { id: 81, name: "Veg Manchow Soup", price: 130, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (81).webp" },
    { id: 82, name: "Chicken Manchow Soup", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (82).webp" },
    { id: 83, name: "Paneer Chilli", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (83).webp" },
    { id: 84, name: "Chicken Chilli", price: 220, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (85).webp" },
    { id: 85, name: "Veg Kurkure Momos", price: 150, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (85).webp" },
    { id: 86, name: "Chicken Kurkure Momos", price: 160, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (86).webp" },
    { id: 87, name: "Paneer Bhatura", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (87).webp" },
    { id: 88, name: "Keema Bhatura", price: 200, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (88).webp" },
    { id: 89, name: "Veg Idli", price: 120, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (89).webp" },
    { id: 90, name: "Chicken Idli", price: 150, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (90).webp" },
    { id: 91, name: "Paneer Masala", price: 210, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (91).webp" },
    { id: 92, name: "Chicken Masala", price: 250, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (92).webp" },
    { id: 93, name: "Veg Stew", price: 160, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (93).webp" },
    { id: 94, name: "Mutton Stew", price: 280, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (95).webp" },
    { id: 95, name: "Paneer Curry", price: 200, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (95).webp" },
    { id: 96, name: "Fish Curry Special", price: 260, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (96).webp" },
    { id: 97, name: "Veg Masala Rice", price: 170, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (97).webp" },
    { id: 98, name: "Egg Masala Rice", price: 190, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (98).webp" },
    { id: 99, name: "Paneer Pulusu", price: 180, restid: 1, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (99).webp" },
    { id: 100, name: "Chicken Pulusu", price: 220, restid: 1, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (100).webp" }
];