export const Data = [
 

//////////    PR GRAND 

////veg starters

{ id: 725, name: "Gobi Manchuria", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 726, name: "Gobi 65", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 727, name: "Gobi Chilly", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 728, name: "Gobi Pepper", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 729, name: "Paneer Chilly", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 730, name: "Paneer Manchuria", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 731, name: "Veg Manchuria", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 732, name: "Mushroom Chilly", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 733, name: "Mushroom solden", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 734, name: "Mushroom solden And Pepper", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 735, name: "Pepper Mushroom", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 736, name: "Mushroom Manchuria", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 737, name: "Baby Corn Chilly", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 738, name: "Baby Corn 65", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 739, name: "Baby Corn Sismiss Fry", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 740, name: "Veg Basket", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 741, name: "Paneer 65", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 742, name: "Kaju Paneer", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 743, name: "Veg Shangrila", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 744, name: "Golden Paneer", price: 210, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 745, name: "Dragon Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
//non-veg starters
{ id: 746, name: "Chicken 65", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 747, name: "Chicken 555", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 748, name: "Chicken Majestic", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 749, name: "Chicken Manchuria", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 750, name: "Chicken Dragon", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 751, name: "Chicken Lemon", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 752, name: "Chicken Chilly", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 753, name: "Chicken Lollipop (6 pcs)", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 754, name: "Chicken Pepper", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 755, name: "Garlic Chicken", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 756, name: "Kaju Chicken", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 757, name: "Chicken Sezwan", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 758, name: "Chicken Drumsticks (6 pcs)", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 759, name: "Chicken Shangrila", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 760, name: "Chicken Pataka", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 761, name: "Chicken Basket", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 762, name: "Ginger Chicken", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 763, name: "Chicken Gulzar", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 764, name: "Chicken Fried Wings", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 765, name: "Hongkong Chicken", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 766, name: "Chicken Burrani", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 767, name: "Natukodi Fry", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//non-veg mouuton
{ id: 768, name: "Mutton 65", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 769, name: "Mutton Chilly", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 770, name: "Mutton Manchuria", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 771, name: "Mutton Pepper", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 772, name: "Mutton Roast", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//Fastfood
{ id: 773, name: "Egg Noodles", price: 180, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 774, name: "Chicken Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 775, name: "Schezwan Chicken Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 776, name: "Prawns Noodles", price: 220, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 777, name: "Chilli Garlic Chicken Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 778, name: "Mix Non Veg Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 779, name: "Schezwan Egg Noodles", price: 170, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 780, name: "Non Veg Hatka Noodles", price: 200, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 781, name: "Veg Noodles", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 782, name: "Paneer Noodles", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 783, name: "Schezwan Veg Noodles", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 784, name: "Chilli Garlic Veg Noodles", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 785, name: "Veg Hatka Noodles", price: 190, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 786, name: "Mushroom Noodles", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
//fish
{ id: 787, name: "Fish 65", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 788, name: "Fish Chilly", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 789, name: "Fish Pepper", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 790, name: "Apollo Fish", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 791, name: "Fish Fry", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 792, name: "Finger Fish", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 793, name: "Fish Basket", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 794, name: "Fish 555", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 795, name: "Dragon Fish", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 796, name: "Prawns Pepper", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 797, name: "Prawns 65", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 798, name: "Prawns Chilly", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 799, name: "Prawns Manchuria", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 800, name: "Loose Prawns", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 801, name: "Golden Prawns", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//egg
{ id: 802, name: "Egg 65", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 803, name: "Egg Chilly", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 804, name: "Egg Bhurji", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 805, name: "Egg Manchuria", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 806, name: "Egg Basket", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 807, name: "Boiled Egg (1 pc)", price: 20, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//egg curries
{ id: 808, name: "Egg curry", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 809, name: "Egg Masala", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 810, name: "Egg fry", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 811, name: "Egg Butter", price: 160, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//tandoori-veg
{ id: 812, name: "Paneer Tikka", price: 280, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 813, name: "Paneer Tranga", price: 290, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 814, name: "Veg Seekh Kabab", price: 250, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 815, name: "Gobi Tikka", price: 250, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 816, name: "Mushroom Tikka", price: 280, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 817, name: "Haraburra Kabab", price: 280, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
//non-vegTandoori & Kababs
{ id: 818, name: "Chicken Tikka", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 819, name: "Chicken Tandoori (Full)", price: 600, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 820, name: "Chicken Tandoori (Half)", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 821, name: "Tangdi Kabab (Full)", price: 300, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 822, name: "Tangdi Kabab (Half)", price: 150, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 823, name: "Malai Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 824, name: "Reshmi Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 825, name: "Garlic Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 826, name: "Hyderabadi Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 827, name: "Mutton Seekh Kabab", price: 400, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 828, name: "Chicken Seekh Kabab", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 829, name: "Haryani Kabab", price: 315, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//veg curries
{ id: 830, name: "Paneer Butter Masala", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 831, name: "Paneer Sahi Kurma", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 832, name: "Paneer Do Pyaz", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 833, name: "Paneer Mutter", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 834, name: "Paneer Tikka Masala", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 835, name: "Palak Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 836, name: "Kadai Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 837, name: "Kaju Paneer Curry", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 838, name: "Kaju Curry", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 839, name: "Kaju Masala", price: 230, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 840, name: "Mix Veg Curry", price: 200, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 841, name: "Plain Palak", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 842, name: "Methi Chaman", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 843, name: "Malai Kofta", price: 240, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 844, name: "Malai Paneer", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 845, name: "Veg Kolhapuri", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 846, name: "Tomato Curry", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 847, name: "Gobi Masala", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 848, name: "Veg Bavarchi (SPL)", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 849, name: "Veg Nawabi (SPL)", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 850, name: "Aloo Gobi Masala", price: 160, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 851, name: "Veg Do Pyaz", price: 170, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 852, name: "Veg Hyderabad", price: 180, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 853, name: "Mushroom Masala", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 854, name: "Mushroom Curry", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
{ id: 855, name: "Kadi Mushroom", price: 220, restid: 8, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/1 (200).webp" },
//non-veg chicken curries
{ id: 856, name: "Butter Chicken", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 857, name: "Chicken Masala", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 858, name: "Chicken Bawarchi", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 859, name: "Chicken Nawabi", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 860, name: "Kadai Chicken", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 861, name: "Chicken Bone Curry", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 862, name: "Chicken Curry", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 863, name: "Andhra Chicken Curry", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 864, name: "Gongura Chicken Curry", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 865, name: "Chicken H0yderabadi", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 866, name: "Chicken Hundi", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 867, name: "Chicken Do Pyaz", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 868, name: "Chicken Rayalseema", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 869, name: "Chicken Patyala", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 870, name: "Chicken Punjabi", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 871, name: "Chicken Afghani", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 872, name: "Chicken Kolhapuri", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 873, name: "Chicken Tikka Masala", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 874, name: "Chicken Kaju Curry", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 875, name: "Chicken Tangadi Masala", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 876, name: "Methi Chicken", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 877, name: "Chicken Lajawab", price: 250, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 878, name: "Chicken Mughlai", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 879, name: "Chicken Maharaja", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 880, name: "Chicken Singapore (Bone)", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 881, name: "Chicken Maharani", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 882, name: "Chicken Mandakini", price: 260, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 883, name: "Natukodi Pulusu", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 884, name: "Natukodi Curry", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//Mutton curries
{ id: 885, name: "Mutton Masala", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 886, name: "Mutton Bawarchi", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 887, name: "Mutton Nawabi", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 888, name: "Kadai Mutton", price: 310, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 889, name: "Mutton Hyderabadi", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 890, name: "Mutton Hundi", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 891, name: "Mutton Do Pyaz", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 892, name: "Mutton Rojan", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 893, name: "Mutton Mughlai", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 894, name: "Methi Mutton", price: 320, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 895, name: "Mutton Keema Curry", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 896, name: "Andhra Mutton", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 897, name: "Mutton Kolhapuri", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 898, name: "Mutton Curry", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 899, name: "Mutton Singapore", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 900, name: "Gongura Mutton Curry", price: 340, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//fish curries
{ id: 901, name: "Fish Curry", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 902, name: "Fish Masala", price: 270, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 903, name: "Rayalaseema Fish Curry", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 904, name: "Prawns Masala", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
{ id: 905, name: "Prawns Curry", price: 280, restid: 8, button: "Add", type: "non-veg", symbol: "🔺", image: "/fooditems/1 (200).webp" },
//NON VEG FRIED RICE
{ id: 906, name: "Chicken Fried Rice", price: 200, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 907, name: "Egg Fried Rice", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 908, name: "Mix Non Veg Fried Rice", price: 210, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 909, name: "Chicken Schezwan Fried Rice", price: 210, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
//VEG FRIED RICE
{ id: 910, name: "Veg Fried Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 911, name: "Veg Gobi Fried Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 912, name: "Veg Mushroom Fried Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 913, name: "Paneer Fried Rice", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 914, name: "Kaju Fried Rice", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 915, name: "Veg Schezwan Fried Rice", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 916, name: "Tomato Rice", price: 160, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 917, name: "Jeera Rice", price: 180, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 918, name: "Ghee Rice", price: 190, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 919, name: "Curd Rice", price: 100, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 920, name: "Plain Curd", price: 30, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
//ROTI'S
{ id: 921, name: "Tandoori Roti", price: 30, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 922, name: "Butter Roti", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 923, name: "Plain Naan", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 924, name: "Butter Naan", price: 45, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 925, name: "Tandoori Parota (1)", price: 35, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 926, name: "Aloo Parota", price: 60, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 927, name: "Rumali Roti", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 928, name: "Lacha Parota", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 929, name: "Kulcha", price: 40, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 930, name: "Masala Kulcha", price: 60, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 931, name: "Pudina Parota", price: 50, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 932, name: "Garlic Naan", price: 50, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 933, name: "Methi Roti", price: 45, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 934, name: "Cheese Naan", price: 60, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 935, name: "Butter Kulcha", price: 50, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 936, name: "Paneer Kulcha", price: 60, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
//VEG DUM BIRYANI
{ id: 937, name: "Veg Dum Biryani", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 938, name: "Kaju Dom Biryani", price: 230, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 939, name: "Paneer Biryani", price: 220, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 940, name: "Mushroom Biryani", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 941, name: "Veg Palav", price: 200, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
//BIRYANIS' NON VEG
{ id: 942, name: "PR Grand Spl Chicken Biryani", price: 310, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 943, name: "Chicken Dum Biryani", price: 240, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 944, name: "Chicken Lollipop Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 945, name: "Chicken Roast Biryani", price: 270, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 946, name: "Mogalai Chicken Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 947, name: "Ulava Charu Chicken Biryani", price: 290, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 948, name: "Gongura Chicken Biryani", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 949, name: "Biryani Rice", price: 170, restid: 5, button: "Add", type: "veg", symbol: "🟢", image: "/fooditems/placeholder.webp" },
{ id: 950, name: "PR Grand Spl Mutton Biryani", price: 360, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 951, name: "Mutton Biryani", price: 320, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 952, name: "Gongura Mutton Biryani", price: 340, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 953, name: "Ulava Charu Mutton Biryani", price: 350, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 954, name: "Mutton Keema Biryani", price: 330, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 955, name: "Egg Biryani", price: 180, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 956, name: "Fish Biryani", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 957, name: "Prawns Biryani", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 958, name: "Tangadi Biryani", price: 290, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 959, name: "Tandoori Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 960, name: "Tikka Chicken Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 961, name: "Natu Kodi Biryani", price: 280, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 962, name: "Kamju Biryani", price: 260, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 963, name: "Potlam Chicken Biryani", price: 300, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },



//comboes and family packs


{ id: 964, name: "Chicken Biryani Family Pack", price: 800, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 965, name: "Chicken Biryani Combo Pack", price: 1100, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 964, name: "Mutton Biryani Family Pack", price: 1000, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },
{ id: 964, name: "Mutton Biryani Combo Pack", price: 1480, restid: 5, button: "Add", type: "non-veg", symbol: "🔴", image: "/fooditems/placeholder.webp" },






]